
[general]

servername=dev.whalesanctuary.co.uk
enabled=yes
bindaddr=0.0.0.0
bindport=8088

tlsenable=yes               ; enable tls - default no.
tlsbindaddr=0.0.0.0:8089    ; address and port to bind to - default is bindaddr and port 8089.
tlscertfile=/etc/asterisk/keys/asterisk.crt    ; path to the certificate file (*.pem) only.
tlsprivatekey=/etc/asterisk/keys/asterisk.key    ; path to private key file (*.pem) only.

;tlsdisablev1=yes                ; Disable TLSv1 support - if not set this defaults to "yes"
;tlsdisablev11=yes               ; Disable TLSv1.1 support - if not set this defaults to "no"
