[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.18.0.0/16
external_media_address=161.97.106.134
external_signaling_address=161.97.106.134

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089
external_media_address=161.97.106.134
external_signaling_address=161.97.106.134

; ===== Configuration du SIP Trunk Opérateur =====

; Authentification pour le trunk
[trunk_operateur_auth]
type=auth
auth_type=userpass
username=62908521
password=167d458f-8
realm=asterisk

; Enregistrement auprès de l'opérateur
[trunk_operateur_reg]
type=registration
transport=transport-udp
outbound_auth=trunk_operateur_auth
server_uri=sip:197.234.218.195:25060
client_uri=sip:62908521@197.234.218.195:25060
retry_interval=60

; AOR du trunk
[trunk_operateur_aor]
type=aor
contact=sip:197.234.218.195:25060

; Identification par IP (appels entrants du trunk)
[trunk_operateur_identify]
type=identify
endpoint=trunk_operateur_endpoint
match=197.234.218.195

; Endpoint du trunk
[trunk_operateur_endpoint]
type=endpoint
context=from-trunk
disallow=all
allow=alaw,ulaw
transport=transport-udp
aors=trunk_operateur_aor
outbound_auth=trunk_operateur_auth
from_user=62908521
from_domain=197.234.218.195
; Ajout des paramètres pour corriger les problèmes de NAT/RTP (coupure après 3s)
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
