services:
  asterisk-omniqa:
    image: andrius/asterisk
    container_name: asterisk-omniqa
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5038:5038/tcp"
      - "10000-20000:10000-20000/udp"
    environment:
      - ASTERISK_USERNAME=admin # Nom d'utilisateur AMI
      - ASTERISK_PASSWORD=your_password # Mot de passe AMI
    volumes:
      - ./asterisk-config:/etc/asterisk # Monter les fichiers de configuration locaux dans le conteneur
    depends_on:
      - db
    networks:
      - asterisk_network
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: asterisk
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: asterisk
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432" # Exposer le port pour le développement local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asterisk -d asterisk"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - asterisk_network
    restart: unless-stopped

  api:
    build: .
    container_name: node-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      asterisk-omniqa:
        condition: service_started
    networks:
      - asterisk_network
    restart: unless-stopped

networks:
  asterisk_network:
    driver: bridge
