[general]
static=no
writeprotect=no
clearglobalvars=no

[default]
exten => 1000,1,Dial(SIP/1000)
exten => 2000,1,Dial(SIP/2000)

[from-internal]
; Appels sortants via Twilio
exten => _X.,1,NoOp(Appel sortant via Twilio)
 same => n,Dial(SIP/+${EXTEN}@twilio,30)  ; Route les appels vers Twilio
 same => n,Hangup()