[modules]
autoload = yes

; Charge explicitement les modules nécessaires
load => res_config_pgsql.so
load => res_pgsql.so
load => chan_sip.so
load => pbx_config.so
load => manager.so

; Si tu n'utilises pas PJSIP, tu peux le désactiver
noload => chan_pjsip.so
noload => res_pjsip.so
noload => res_pjsip_session.so