[general]
context=public                ; Default context for incoming calls
allowguest=no                 ; Allow or reject guest calls (default is yes)
udpbindaddr=0.0.0.0:5060      ; UDP address to bind to
tcpenable=no                  ; Enable server for incoming TCP connections (default is no)
transport=udp                 ; Set the default transport type to UDP

; Configuration Realtime
rtcachefriends=yes            ; Cache Realtime friends by adding them to the internal list
rtsave=no                     ; Don't update the database on registry, qualify, etc
rtautoclear=yes               ; Auto-expire cached Realtime users 
