services:
  asterisk:
    build: .
    volumes:
      - "${PWD}/etc/asterisk:/etc/asterisk"
      - "/etc/asterisk/certs:/etc/asterisk/keys:ro"
      - "${PWD}/log/asterisk:/var/log/asterisk"
      - "${PWD}/odbc.ini:/etc/odbc.ini"
      - "${PWD}/odbcinst.ini:/etc/odbcinst.ini"
      - "${PWD}/log/supervisor:/var/log/supervisor"
    ports:
      - "5038:5038" # AMI
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/udp"
      - "5061:5061/tcp"
      - "8088:8088" # HTTP
      - "8089:8089" # HTTPS / WSS
      - "10000-10200:10000-10200/udp" # RTP
    restart: always
    #network_mode: host

  db:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_IMAGE_VERSION:-12}
    environment:
      POSTGRES_DB: "asterisk"
      POSTGRES_USER: "asterisk"
      POSTGRES_PASSWORD: "Obelix"
    volumes:
      - "${PWD}/.pgdata:/var/lib/postgresql/data"
      - "${PWD}/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro"
      - "${PWD}/init.sql:/docker-entrypoint-initdb.d/02-init.sql:ro"
    ports:
      - "5432:5432"
    restart: always
