import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1762588463699 implements MigrationInterface {
    name = 'InitialSchema1762588463699'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenant_contexts" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "name" character varying(100) NOT NULL, "description" text, "is_primary" boolean NOT NULL DEFAULT false, "dialplan_config" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1080f9e6c31360a779359da1527" UNIQUE ("name"), CONSTRAINT "PK_ceecee7b4b22f7c0d82ef47cf19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f56efdc048de3e147814da5c8a" ON "tenant_contexts" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1080f9e6c31360a779359da152" ON "tenant_contexts" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dc62f40a5e8d7c675e40a1ff67" ON "tenant_contexts" ("tenant_id", "is_primary") WHERE is_primary = true`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "company_name" character varying, "contact_email" character varying, "contact_phone" character varying(50), "address" text, "city" character varying(100), "country" character varying(100), "timezone" character varying(50) NOT NULL DEFAULT 'UTC', "is_active" boolean NOT NULL DEFAULT true, "max_endpoints" integer NOT NULL DEFAULT '100', "max_queues" integer NOT NULL DEFAULT '50', "dialplan_config" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "endpoint_roles" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "name" character varying(50) NOT NULL, "display_name" character varying(100) NOT NULL, "description" text, "level" integer NOT NULL DEFAULT '1', "can_call_same_level" boolean NOT NULL DEFAULT true, "can_call_lower_level" boolean NOT NULL DEFAULT false, "can_call_higher_level" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_495a93e171b4434c9e5bc9e72f8" UNIQUE ("tenant_id", "level"), CONSTRAINT "UQ_87c81c54adc595a78c5dec4b792" UNIQUE ("tenant_id", "name"), CONSTRAINT "CHK_cbb0e74c322e1dd43111535c9f" CHECK ("level" >= 1 AND "level" <= 10), CONSTRAINT "PK_51ba684e88411e00f014e953839" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "call_audit_logs" ("id" BIGSERIAL NOT NULL, "tenant_id" integer NOT NULL, "caller_endpoint_id" character varying(40), "caller_role_id" integer, "called_endpoint_id" character varying(40), "called_role_id" integer, "caller_context" character varying(128), "called_context" character varying(128), "action" character varying(20) NOT NULL, "deny_reason" character varying(100), "channel_id" character varying(100), "uniqueid" character varying(100), "caller_number" character varying(40), "called_number" character varying(40), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7221bc15fbe6cf34b65e4e0766c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c039a3f885588a454dc66eabe3" ON "call_audit_logs" ("tenant_id", "action", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_c844853c7254e19a6e0340da97" ON "call_audit_logs" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_edd1d8f530db7faac9eb00dd09" ON "call_audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2f5aa54083e28e8de339454fc" ON "call_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_359b6b2ef09667ed2f97af0ca6" ON "call_audit_logs" ("called_endpoint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6dd8612fa8cd3c6b7f9fc1180" ON "call_audit_logs" ("caller_endpoint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d86c93b4e1e46b385ae50a87" ON "call_audit_logs" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "sip_trunks" ("id" SERIAL NOT NULL, "name" character varying(40) NOT NULL, "tenant_id" integer NOT NULL, "remote_host" character varying(255) NOT NULL, "username" character varying(100) NOT NULL, "password" character varying(100) NOT NULL, "transport" character varying(40) NOT NULL DEFAULT 'transport-udp', "context" character varying(100) NOT NULL DEFAULT 'from-trunk', "sends_registrations" boolean NOT NULL DEFAULT true, "sends_auth" boolean NOT NULL DEFAULT true, "client_uri" character varying(255), "server_uri" character varying(255), "retry_interval" integer NOT NULL DEFAULT '60', "expiration" integer NOT NULL DEFAULT '3600', "max_retries" integer NOT NULL DEFAULT '10', "forbidden_retry_interval" integer NOT NULL DEFAULT '0', "line" boolean NOT NULL DEFAULT false, "outbound_proxy" character varying(255), "support_path" boolean NOT NULL DEFAULT false, "display_name" character varying(100), "description" text, "enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3016f4c6d6e4bc1148a5829aa83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "call_recordings" ("id" SERIAL NOT NULL, "tenant_id" integer, "uniqueid" character varying(150) NOT NULL, "filename" character varying(255) NOT NULL, "filepath" character varying(500) NOT NULL, "format" character varying(10), "duration" integer, "filesize" bigint, "src" character varying(80), "dst" character varying(80), "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4825dd582adb1f8c2f29cf74106" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a2a9aa3b031b4aefb46b14e5b" ON "call_recordings" ("tenant_id", "uniqueid") `);
        await queryRunner.query(`CREATE INDEX "IDX_b89e80ba3df019d49852931838" ON "call_recordings" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."ivr_conditions_condition_type_enum" AS ENUM('time', 'caller_id', 'did', 'custom')`);
        await queryRunner.query(`CREATE TABLE "ivr_conditions" ("id" SERIAL NOT NULL, "menu_id" integer NOT NULL, "tenant_id" integer NOT NULL, "condition_type" "public"."ivr_conditions_condition_type_enum" NOT NULL, "condition_config" jsonb NOT NULL, "action" jsonb NOT NULL, "priority" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_086be9257288237633d994dcc5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ivr_menus" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "name" character varying NOT NULL, "description" character varying, "welcome_sound" character varying NOT NULL, "invalid_sound" character varying, "timeout_sound" character varying, "timeout" integer NOT NULL DEFAULT '5', "max_retries" integer NOT NULL DEFAULT '3', "max_digits" integer NOT NULL DEFAULT '1', "timeout_action" jsonb NOT NULL, "invalid_action" jsonb NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf255d4fd33a920d2bc23c4a94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ivr_options" ("id" SERIAL NOT NULL, "menu_id" integer NOT NULL, "tenant_id" integer NOT NULL, "digit" character varying(1) NOT NULL, "action" jsonb NOT NULL, "description" character varying, "priority" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_105555e3e3b503d66e8d570b429" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "queues" ("name" character varying(128) NOT NULL, "tenant_id" integer NOT NULL, "strategy" character varying(128), "timeout" integer, "retry" integer, "maxlen" integer, "weight" integer, "announce_position" character varying(128), "announce_holdtime" character varying(128), "musiconhold" character varying(128), "announce_frequency" integer, "min_announce_frequency" integer, "servicelevel" integer, "joinempty" character varying(128), "leavewhenempty" character varying(128), "ringinuse" character varying, "memberdelay" integer, "wrapuptime" integer, "autopause" character varying, "periodic_announce" character varying(50), "periodic_announce_frequency" integer, "context" character varying(128) NOT NULL, "announce" character varying(128), CONSTRAINT "PK_a290d70c28ba7f1c5d2600da849" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "ivr_did_mappings" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "did" character varying NOT NULL, "menu_id" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_13b92b63e960abbdc180045aca6" UNIQUE ("tenant_id", "did"), CONSTRAINT "PK_f57d498e3a08d8c94dadde40a74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "queue_members" ("tenant_id" integer NOT NULL, "queue_name" character varying(128) NOT NULL, "interface" character varying(128) NOT NULL, "membername" character varying(80), "penalty" integer NOT NULL DEFAULT '0', "paused" integer NOT NULL DEFAULT '0', "wrapuptime" integer DEFAULT '0', "state_interface" character varying(80), "uniqueid" integer NOT NULL, CONSTRAINT "PK_a0d47c4cbf43e43f9a888af2b71" PRIMARY KEY ("tenant_id", "queue_name", "interface"))`);
        await queryRunner.query(`CREATE TABLE "ivr_audio_files" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "name" character varying NOT NULL, "filename" character varying NOT NULL, "filepath" character varying NOT NULL, "format" character varying NOT NULL, "duration" double precision NOT NULL, "language" character varying, "filesize" bigint NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a17c2414a72d81b8869a69da58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ps_aors" ("id" character varying(40) NOT NULL, "tenant_id" integer, "max_contacts" integer DEFAULT '1', "remove_existing" character varying(3) DEFAULT 'no', "minimum_expiration" integer DEFAULT '60', "maximum_expiration" integer DEFAULT '3600', "default_expiration" integer DEFAULT '3600', "qualify_frequency" integer DEFAULT '0', "qualify_timeout" real DEFAULT '3', "authenticate_qualify" character varying(3) DEFAULT 'no', "support_path" character varying(3) DEFAULT 'no', "mailboxes" character varying(200), "created_at" TIMESTAMP DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_265dfd1870d6bed76a540d9cb4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ps_auths" ("id" character varying(40) NOT NULL, "tenant_id" integer, "auth_type" character varying(20) DEFAULT 'userpass', "username" character varying(40), "password" character varying(80), "md5_cred" character varying(40), "realm" character varying(40), "nonce_lifetime" integer DEFAULT '32', "created_at" TIMESTAMP DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_b5f97af54ea96fbedad6b64fa24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ps_endpoints" ("id" character varying(40) NOT NULL, "display_name" character varying(40), "tenant_id" integer, "transport" character varying(40), "aors" character varying(200), "auth" character varying(200), "context" character varying(40) DEFAULT 'default', "disallow" character varying(200) DEFAULT 'all', "allow" character varying(200) DEFAULT 'ulaw,alaw', "direct_media" character varying(3) DEFAULT 'yes', "trust_id_inbound" character varying(3) DEFAULT 'no', "send_pai" character varying(3) DEFAULT 'no', "send_rpid" character varying(3) DEFAULT 'no', "callerid" character varying(40), "dtmf_mode" character varying(20) DEFAULT 'rfc4733', "ice_support" character varying(3) DEFAULT 'no', "mailboxes" character varying(100), "webrtc" character varying(3) DEFAULT 'no', "use_avpf" character varying(3) DEFAULT 'no', "media_encryption" character varying(20), "dtls_verify" character varying(20), "dtls_setup" character varying(20), "dtls_cert_file" character varying(200), "dtls_private_key" character varying(200), "dtls_ca_file" character varying(200), "rtcp_mux" character varying(3) DEFAULT 'no', "rtp_symmetric" character varying(3) DEFAULT 'no', "force_rport" character varying(3) DEFAULT 'no', "rewrite_contact" character varying(3) DEFAULT 'no', "identify_by" character varying(80) DEFAULT 'username', "bundle" character varying(3) DEFAULT 'no', "timers" character varying(3) DEFAULT 'yes', "role_id" integer, "created_at" TIMESTAMP DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_e6f3c9a4a71d193e36cbcdb2f19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extensions" ("id" BIGSERIAL NOT NULL, "tenant_id" integer NOT NULL, "context" character varying(40) NOT NULL, "exten" character varying(40) NOT NULL, "priority" integer NOT NULL, "app" character varying(40) NOT NULL, "appdata" character varying(256) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_db4da70af7c0121d6d4ae682dbd" UNIQUE ("tenant_id", "context", "exten", "priority"), CONSTRAINT "PK_3632b8148c8f511650d3f3eda06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8175f1923b8d9516157c5ff24b" ON "extensions" ("exten") `);
        await queryRunner.query(`CREATE INDEX "IDX_84a5670af6763d4dddc5674e73" ON "extensions" ("context") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5da27bdeeac76107ac4ffcc1b" ON "extensions" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."app_users_role_enum" AS ENUM('admin', 'tenant_admin', 'supervisor', 'agent')`);
        await queryRunner.query(`CREATE TABLE "app_users" ("id" SERIAL NOT NULL, "tenant_id" integer, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."app_users_role_enum" NOT NULL DEFAULT 'agent', "first_name" character varying(100), "last_name" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_14241fb016a330600a7e0efae93" UNIQUE ("email"), CONSTRAINT "PK_9b97e4fbff9c2f3918fda27f999" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cdr" ("id" SERIAL NOT NULL, "tenant_id" integer, "calldate" TIMESTAMP NOT NULL DEFAULT now(), "clid" character varying(80) NOT NULL DEFAULT '', "src" character varying(80) NOT NULL DEFAULT '', "dst" character varying(80) NOT NULL DEFAULT '', "dcontext" character varying(80) NOT NULL DEFAULT '', "channel" character varying(80) NOT NULL DEFAULT '', "dstchannel" character varying(80) NOT NULL DEFAULT '', "lastapp" character varying(80) NOT NULL DEFAULT '', "lastdata" character varying(80) NOT NULL DEFAULT '', "duration" integer NOT NULL DEFAULT '0', "billsec" integer NOT NULL DEFAULT '0', "disposition" character varying(45) NOT NULL DEFAULT '', "amaflags" integer NOT NULL DEFAULT '0', "accountcode" character varying(50) NOT NULL DEFAULT '', "uniqueid" character varying(32) NOT NULL DEFAULT '', "userfield" character varying(150) NOT NULL DEFAULT '', "peeraccount" character varying(32), "linkedid" character varying(32), "sequence" integer, CONSTRAINT "PK_0d5afbe6ea3365788ca99fa9a8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91b3ffeed8a14abecef7429a64" ON "cdr" ("tenant_id", "disposition") `);
        await queryRunner.query(`CREATE INDEX "IDX_c29263875d6a2463266a5e08ee" ON "cdr" ("tenant_id", "dst") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f8f16e820798157b639f850d7" ON "cdr" ("tenant_id", "src") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cb6c0afb517b4a3923b208154" ON "cdr" ("tenant_id", "calldate") `);
        await queryRunner.query(`ALTER TABLE "tenant_contexts" ADD CONSTRAINT "FK_f56efdc048de3e147814da5c8ae" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "endpoint_roles" ADD CONSTRAINT "FK_36ec225395ebc98f82244140434" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "call_audit_logs" ADD CONSTRAINT "FK_47d86c93b4e1e46b385ae50a870" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "call_audit_logs" ADD CONSTRAINT "FK_57c374d3dc0d7b1e185c9b03d93" FOREIGN KEY ("caller_role_id") REFERENCES "endpoint_roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "call_audit_logs" ADD CONSTRAINT "FK_9f952b4506b56c54aefa38eff00" FOREIGN KEY ("called_role_id") REFERENCES "endpoint_roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sip_trunks" ADD CONSTRAINT "FK_e3c1e80d210f0886e4323155408" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_conditions" ADD CONSTRAINT "FK_6e7a134535f178739b310afa742" FOREIGN KEY ("menu_id") REFERENCES "ivr_menus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_conditions" ADD CONSTRAINT "FK_44f4a664a32500bf0bf028b7070" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_menus" ADD CONSTRAINT "FK_7b9f8c8122c85a99cc3f1406137" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_options" ADD CONSTRAINT "FK_39687ce0aad186a504bef395037" FOREIGN KEY ("menu_id") REFERENCES "ivr_menus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_options" ADD CONSTRAINT "FK_c56f398e2b5250a8bec81ed06f9" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queues" ADD CONSTRAINT "FK_1caa5edd6bd193924bcf09d3e6c" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_did_mappings" ADD CONSTRAINT "FK_c56eeb49686e74e8a11490f1136" FOREIGN KEY ("menu_id") REFERENCES "ivr_menus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_did_mappings" ADD CONSTRAINT "FK_494919b7f4a1be1451ec3cf0437" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_members" ADD CONSTRAINT "FK_ff0eb96c87d65c7107b8f023ff3" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivr_audio_files" ADD CONSTRAINT "FK_97cb6e8e9a16ce350a70f55ab0a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ps_aors" ADD CONSTRAINT "FK_dec46f09139cbc4160b0ebca8f4" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ps_auths" ADD CONSTRAINT "FK_5f9c26257bca97e3356ab4fae23" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ps_endpoints" ADD CONSTRAINT "FK_4e68f253ba0af61e93ebabca11a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ps_endpoints" ADD CONSTRAINT "FK_2e29c9fdfd54175774c95310c11" FOREIGN KEY ("role_id") REFERENCES "endpoint_roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extensions" ADD CONSTRAINT "FK_a5da27bdeeac76107ac4ffcc1ba" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_users" ADD CONSTRAINT "FK_1d23fa58deeb2e36db749276775" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "app_users" DROP CONSTRAINT "FK_1d23fa58deeb2e36db749276775"`);
        await queryRunner.query(`ALTER TABLE "extensions" DROP CONSTRAINT "FK_a5da27bdeeac76107ac4ffcc1ba"`);
        await queryRunner.query(`ALTER TABLE "ps_endpoints" DROP CONSTRAINT "FK_2e29c9fdfd54175774c95310c11"`);
        await queryRunner.query(`ALTER TABLE "ps_endpoints" DROP CONSTRAINT "FK_4e68f253ba0af61e93ebabca11a"`);
        await queryRunner.query(`ALTER TABLE "ps_auths" DROP CONSTRAINT "FK_5f9c26257bca97e3356ab4fae23"`);
        await queryRunner.query(`ALTER TABLE "ps_aors" DROP CONSTRAINT "FK_dec46f09139cbc4160b0ebca8f4"`);
        await queryRunner.query(`ALTER TABLE "ivr_audio_files" DROP CONSTRAINT "FK_97cb6e8e9a16ce350a70f55ab0a"`);
        await queryRunner.query(`ALTER TABLE "queue_members" DROP CONSTRAINT "FK_ff0eb96c87d65c7107b8f023ff3"`);
        await queryRunner.query(`ALTER TABLE "ivr_did_mappings" DROP CONSTRAINT "FK_494919b7f4a1be1451ec3cf0437"`);
        await queryRunner.query(`ALTER TABLE "ivr_did_mappings" DROP CONSTRAINT "FK_c56eeb49686e74e8a11490f1136"`);
        await queryRunner.query(`ALTER TABLE "queues" DROP CONSTRAINT "FK_1caa5edd6bd193924bcf09d3e6c"`);
        await queryRunner.query(`ALTER TABLE "ivr_options" DROP CONSTRAINT "FK_c56f398e2b5250a8bec81ed06f9"`);
        await queryRunner.query(`ALTER TABLE "ivr_options" DROP CONSTRAINT "FK_39687ce0aad186a504bef395037"`);
        await queryRunner.query(`ALTER TABLE "ivr_menus" DROP CONSTRAINT "FK_7b9f8c8122c85a99cc3f1406137"`);
        await queryRunner.query(`ALTER TABLE "ivr_conditions" DROP CONSTRAINT "FK_44f4a664a32500bf0bf028b7070"`);
        await queryRunner.query(`ALTER TABLE "ivr_conditions" DROP CONSTRAINT "FK_6e7a134535f178739b310afa742"`);
        await queryRunner.query(`ALTER TABLE "sip_trunks" DROP CONSTRAINT "FK_e3c1e80d210f0886e4323155408"`);
        await queryRunner.query(`ALTER TABLE "call_audit_logs" DROP CONSTRAINT "FK_9f952b4506b56c54aefa38eff00"`);
        await queryRunner.query(`ALTER TABLE "call_audit_logs" DROP CONSTRAINT "FK_57c374d3dc0d7b1e185c9b03d93"`);
        await queryRunner.query(`ALTER TABLE "call_audit_logs" DROP CONSTRAINT "FK_47d86c93b4e1e46b385ae50a870"`);
        await queryRunner.query(`ALTER TABLE "endpoint_roles" DROP CONSTRAINT "FK_36ec225395ebc98f82244140434"`);
        await queryRunner.query(`ALTER TABLE "tenant_contexts" DROP CONSTRAINT "FK_f56efdc048de3e147814da5c8ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cb6c0afb517b4a3923b208154"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f8f16e820798157b639f850d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c29263875d6a2463266a5e08ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91b3ffeed8a14abecef7429a64"`);
        await queryRunner.query(`DROP TABLE "cdr"`);
        await queryRunner.query(`DROP TABLE "app_users"`);
        await queryRunner.query(`DROP TYPE "public"."app_users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5da27bdeeac76107ac4ffcc1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84a5670af6763d4dddc5674e73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8175f1923b8d9516157c5ff24b"`);
        await queryRunner.query(`DROP TABLE "extensions"`);
        await queryRunner.query(`DROP TABLE "ps_endpoints"`);
        await queryRunner.query(`DROP TABLE "ps_auths"`);
        await queryRunner.query(`DROP TABLE "ps_aors"`);
        await queryRunner.query(`DROP TABLE "ivr_audio_files"`);
        await queryRunner.query(`DROP TABLE "queue_members"`);
        await queryRunner.query(`DROP TABLE "ivr_did_mappings"`);
        await queryRunner.query(`DROP TABLE "queues"`);
        await queryRunner.query(`DROP TABLE "ivr_options"`);
        await queryRunner.query(`DROP TABLE "ivr_menus"`);
        await queryRunner.query(`DROP TABLE "ivr_conditions"`);
        await queryRunner.query(`DROP TYPE "public"."ivr_conditions_condition_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b89e80ba3df019d49852931838"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a2a9aa3b031b4aefb46b14e5b"`);
        await queryRunner.query(`DROP TABLE "call_recordings"`);
        await queryRunner.query(`DROP TABLE "sip_trunks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47d86c93b4e1e46b385ae50a87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6dd8612fa8cd3c6b7f9fc1180"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_359b6b2ef09667ed2f97af0ca6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2f5aa54083e28e8de339454fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edd1d8f530db7faac9eb00dd09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c844853c7254e19a6e0340da97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c039a3f885588a454dc66eabe3"`);
        await queryRunner.query(`DROP TABLE "call_audit_logs"`);
        await queryRunner.query(`DROP TABLE "endpoint_roles"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc62f40a5e8d7c675e40a1ff67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1080f9e6c31360a779359da152"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f56efdc048de3e147814da5c8a"`);
        await queryRunner.query(`DROP TABLE "tenant_contexts"`);
    }

}
