services:
  asterisk:
    build: .
    ports:
      - "5038:5038"    # AMI
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/udp"
      - "5061:5061/tcp"
      - "8088:8088"    # HTTP
      - "8089:8089"    # HTTPS
      - "10000-10200:10000-10200/udp"  # RTP
    restart: always
    volumes:
      # Décommenter UN fichier à la fois pour tester
      - "../etc/asterisk/acl.conf:/etc/asterisk/acl.conf"
      - "../etc/asterisk/asterisk.conf:/etc/asterisk/asterisk.conf"
      - "../etc/asterisk/cdr.conf:/etc/asterisk/cdr.conf"
      - "../etc/asterisk/cdr_pgsql.conf:/etc/asterisk/cdr_pgsql.conf"
      - "../etc/asterisk/extconfig.conf:/etc/asterisk/extconfig.conf"
      - "../etc/asterisk/extensions.conf:/etc/asterisk/extensions.conf"
      # - "../etc/asterisk/features.conf:/etc/asterisk/features.conf"
      - "../etc/asterisk/festival.conf:/etc/asterisk/festival.conf"
      - "../etc/asterisk/http.conf:/etc/asterisk/http.conf"
      - "../etc/asterisk/iax.conf:/etc/asterisk/iax.conf"
      - "../etc/asterisk/indications.conf:/etc/asterisk/indications.conf"
      - "../etc/asterisk/logger.conf:/etc/asterisk/logger.conf"
      - "../etc/asterisk/modules.conf:/etc/asterisk/modules.conf"
      - "../etc/asterisk/musiconhold.conf:/etc/asterisk/musiconhold.conf"
      - "../etc/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf"
      - "../etc/asterisk/pjsip_notify.conf:/etc/asterisk/pjsip_notify.conf"
      - "../etc/asterisk/pjsip_wizard.conf:/etc/asterisk/pjsip_wizard.conf"
      - "../etc/asterisk/queues.conf:/etc/asterisk/queues.conf"
      - "../etc/asterisk/res_odbc.conf:/etc/asterisk/res_odbc.conf"
      - "../etc/asterisk/res_pgsql.conf:/etc/asterisk/res_pgsql.conf"
      - "../etc/asterisk/rtp.conf:/etc/asterisk/rtp.conf"
      - "../etc/asterisk/sorcery.conf:/etc/asterisk/sorcery.conf"
